### ISSUE TITLE
your app is not complete

### ISSUE THREAD

**Issue by bokrma** [sundas-arooj/email-client-core#1]
your app is not complete,
the app should have a complete sync of any email data exists on the email provider server in our local database
and it should sync the changes in the data in real life (so cron jobs are the way to fetch the data and keep the sync)
and from what I see in your app, its only syncing the inbox mailbox
you create multiple mailboxes and sub mailboxes and move emails between them and it reflect in the local database

**Comment by sundas-arooj** [comment]
Hi Karim,I appreciate your detailed response, I might missed that, also using cron jobs were not particularly mentioned and webhook was also a way to sync updates so I used that. But if you allow me I can make these changes in the app.Please let me know, ThanksRegards,Sundas Arooj
-------- Original message --------From: Karim Haddad ***@***.***> Date: 17/06/2024  6:19 pm  (GMT+05:00) To: sundas-arooj/email-client-core ***@***.***> Cc: Subscribed ***@***.***> Subject: [sundas-arooj/email-client-core] your app is not complete (Issue #1) 
your app is not complete,
the app should have a complete sync of any email data exists on the email provider server in our local database
and it should sync the changes in the data in real life (so cron jobs are the way to fetch the data and keep the sync)
and from what I see in your app, its only syncing the inbox mailbox
you create multiple mailboxes and sub mailboxes and move emails between them and it reflect in the local database

**Comment by bokrma** [comment]
if you want to do the changes, be sure it will work on a real life situation with all the data fetched from all mailboxes in in. a smart way, considering the missing events could not be send from outlook or the providers you are adding

**Comment by sundas-arooj** [comment]
@bokrma sure making the changes.

**Comment by sundas-arooj** [comment]
Hey @bokrma, I pushed the changes as you mentioned.
